#!/bin/sh

# This script retrieves a pre-compiled war file from a location on the Web
# (Nexus, Jenkins, ...) and deploys it into the JBoss EAP Server.
#
# WAR_FILE_LOCATION: Set in .s2i/environment

DEPLOY_DIR=$JBOSS_HOME/standalone/deployments
APP_NAME=ROOT.war

echo "deploying artifact found at $WAR_FILE_LOCATION to $DEPLOY_DIR/$APP_NAME"
curl --insecure -L -o $DEPLOY_DIR/$APP_NAME $WAR_FILE_LOCATION

exit 0
